---
Default_Model_Greeting:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    hash:
      type: integer
    isEnglish:
      type: boolean
      default: 0
    from_name:
      type: string(255)
    from_email:
      type: string(255)
    signature:
      type: boolean
    greeting:
      type: clob
    seen:
      type: integer
      default: 0
  relations:
    Recipient:
      class: Default_Model_GreetingRecipient
      local: id
      foreign: greeting_id
      type: many
  actAs: [Timestampable]

Default_Model_GreetingRecipient:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    greeting_id:
      type: integer
    to_name:
      type: string(255)
    to_email:
      type: string(255)