---
Default_Model_Greeting:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    hash:
      type: integer
    from_name:
      type: string(255)
    from_email:
      type: string(255)
    greeting:
      type: clob
  relations:
    Recipient:
      class: Default_Model_GreetingRecipient
      local: id
      foreign: greeting_id
  actAs: [Timestampable]

Default_Model_GreetingRecipient:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    greeting_id:
      type: integer
    to_name:
      type: string(255)
    to_email:
      type: string(255)