<div class="grid_4 alpha">
    <h2>Velkommen til Verk Julekort</h2>
    <p>
        Kunne du tænke dig at sende et digitalt julekort til dine kolleger eller bare en ven eller bekendt? Her får du muligheden for at sende en hilsen til en du holder af.
    </p>
    <p><a href="<?php print $this->url(array(
        'controller' => 'index',
        'action'     => 'new'
    )); ?>">Opret din egen hilsen her</a></p>
    <p>
        Har du allerede fået et julekort og ønsker at se kortet, så kan du indtaste din kode til højre.
    </p>
</div>
<div class="grid_4 omega">
    <?php print $this->form; ?>
</div>