<div class="grid_2 alpha">
    <p>
        Her kan du skrive en hilsen til en ven eller bekendt. Udfylde felterne til højre og send din hilsen afsted.
    </p>
    <p>
        Vil du sende en stor stak hilsner på en gang, kan du indtaste alle adresserne sepereret med komma i `Til email´ feltet.
    </p>
    <p>
        Du kan altid se et eksempel af din hilsen ved at klikke på "vis kort".
    </p>
</div>
<div class="grid_3">
    <?php print $this->form; ?>
</div>
<div class="grid_3 omega">
    <div class="flash">&nbsp;</div>
    <div class="flash-text"></div>
</div>