<div class="grid_2 alpha">
    <p>
        Her kan du skrive en julehilsen og sende til en ven, en kunde eller en samarbejdspartner.
    </p>
    <p>
        Du kan sende din hilsen til en eller flere modtagere. Hvis du vi sende samme tekst til flere modtagere, indsætter du blot modtagernes e-mailadresser i “Til e-mail”-feltet med et komma imellem. I “Til”-feltet kan du skrive fx “samarbejds-partner”
    </p>
    <p>
        Hvis du vil sende samme hilsen til forskellige personer med en personlig hilsen, skal du klikke på “Tilføj modtager”
    </p>
    <p>
        Du kan rette i teksten indtil du er tilfreds. Du ser kortet på “Vis kort”, og du sender på “Send kort”.
    </p>
    <p>
        God fornøjelse.
    </p>
</div>
<div class="grid_3 grid_3_norightmargin">
    <?php print $this->form; ?>
</div>
<div class="grid_3 omega">
    <div class="flash">&nbsp;</div>
    <div class="flash-text"></div>
</div>

<div class="grid_6 alpha omega push_2 lightbox">
    <div class="flash">&nbsp;</div>
    <div class="flash-text"></div>
    <button class="close">Tilbage</button>
</div>