<div class="grid_2">
    <p>Her kan du skrive en julehilsen og sende den til en ven eller samarbejdspartner. Du kan se kortet ved at trykke “Vis kort”.</p>
    <p>Hvis du er tilfreds, sender du kortet på “Send kort”. Ellers kan du rette teksten i formularen.</p>
    <p>God fornøjelse</p>
</div>
<div class="grid_3">
    <?php print $this->form; ?>
</div>
<div class="grid_3">
    <div class="flash">&nbsp;</div>
    <div class="flash-text"></div>
</div>