<div class="grid_4 prefix_2 suffix_2">
    <div class="flash">&nbsp;</div>
    <div class="flash-text"><?php print $this->greeting; ?></div>
    <div class="sig">
        <input type="hidden" value="<?php print $this->signature; ?>" name="use-signature" class="use-signature">
    </div>

    <div class="clear"></div>

    <div style="text-align:center">
        <a class="reload-card" href="#">(Vis igen)</a>
    </div>
</div>
