<?php print $this->doctype('HTML5'); ?>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>EBST Julekort</title>
    <meta name="description" content="Julekort for EBST">
    <meta name="author" content="Verk ApS - Christian Kirkegaard">

    <meta name="viewport" content="width=device-width; initial-scale=1.0">

    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">

    <link rel="stylesheet" href="/styles/960.css?v=1" media="screen">
    <link rel="stylesheet" href="/styles/style.css?v=1">

    <script src="/scripts/modernizr-1.5.min.js"></script>

</head>
<body class="step_<?php print $this->step; ?>">

    <div id="container" class="container_12">
        <header class="grid_12">
            <h1>EBST</h1>
        </header>

        <div id="main">
            <?php echo $this->layout()->content; ?>
            <div class="clear"></div>
        </div>

        <footer>
            <p>footer note...
        </footer>
    </div>


    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>
    <script>!window.jQuery && document.write('<script src="/scripts/jquery-1.4.3.min.js"><\/script>')</script>

    <script src="/scripts/jquery.swfobject.min.js"></script>

    <!--[if lt IE 7 ]>
        <script src="/scripts/dd_belatedpng.js?"></script>
        <script>
            DD_belatedPNG.fix('img, .png_bg'); //fix any <img> or .png_bg background-images
        </script>
    <![endif]-->

    <?php print $this->inlineScript(); ?>

    <!-- asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet
        change the UA-XXXXX-X to be your site's ID -->
    <script>
        var _gaq = [['_setAccount', 'UA-XXXXX-X'], ['_trackPageview']];
        (function(d, t) {
        var g = d.createElement(t),
            s = d.getElementsByTagName(t)[0];
        g.async = true;
        g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g, s);
        })(document, 'script');
    </script>

</body>
</html>