<?php print $this->doctype('HTML5'); ?>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html lang="da" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="da" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="da" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="da" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="da" class="no-js"> <!--<![endif]-->
<head>
    <meta charset="UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Inspicos Julekort</title>
    <meta name="description" content="Julekort">
    <meta name="author" content="Verk ApS - Christian Kirkegaard">

    <meta name="viewport" content="width=device-width; initial-scale=1.0">

    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">

    <link rel="stylesheet" href="/styles/960.css?v=1" media="screen">
    <link rel="stylesheet" href="/styles/style.css?v=1">

    <script src="/scripts/modernizr-1.5.min.js"></script>

</head>
<body class="<?php print $this->BodyClass(array('action')); ?>">

    <div id="page" class="container_8">
        <header class="grid_8">
            <div class="grid_2 alpha">
                <img src="/images/europatent.jpg">
            </div>
            <div class="grid_3">
                <a href="/">
                    <img src="/images/logo.jpg">
                </a>
            </div>
            <div class="grid_3 omega julehilsen text-right">
                <img src="/images/julehilsen.jpg">
            </div>

            <div class="clear"></div>

            <div class="menu">
                <div class="grid_3 prefix_2 alpha">
                    www.inspicos.dk
                </div>
                <div class="grid_3 omega text-right">
                    www.inspicos.dk
                </div>
            </div>
        </header>

        <div id="container">
            <div class="grid_8">
                <?php echo $this->layout()->content; ?>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>

        <footer class="grid_8">&nbsp;</footer>
    </div>

    <!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>-->
    <script>!window.jQuery && document.write('<script src="/scripts/jquery-1.4.4.min.js"><\/script>')</script>

    <script src="/scripts/jquery.autogrow.js"></script>
    <script src="/scripts/jquery.charcounter.js"></script>
    <script src="/scripts/jquery.swfobject.min.js"></script>
    <script charset="utf-8" src="/scripts/main.js"></script>

    <!--[if lt IE 7 ]>
        <script src="/scripts/dd_belatedpng.js?"></script>
        <script>
            DD_belatedPNG.fix('img, .png_bg'); //fix any <img> or .png_bg background-images
        </script>
    <![endif]-->

    <?php print $this->inlineScript(); ?>

    <!-- asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet
        change the UA-XXXXX-X to be your site's ID -->
    <!--<script>
        var _gaq = [['_setAccount', 'UA-116454-27'], ['_trackPageview']];
        (function(d, t) {
        var g = d.createElement(t),
            s = d.getElementsByTagName(t)[0];
        g.async = true;
        g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g, s);
        })(document, 'script');
    </script>-->

</body>
</html>