<?php

/**
 * Default_Model_Greeting
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Default_Model_Greeting extends Default_Model_Base_Greeting
{

    public function save(Doctrine_Connection $conn = null)
    {
        if(!$this->id) {
            $this->hash = $this->_generateHash(10);
        }
        return parent::save($conn);
    }

    protected function _generateHash($amount)
    {
        $number = '';
        for($i = 0; $i < $amount; $i++) {
            $number .= mt_rand(0,9);
        }
        return $number;
    }

}